### ISSUE TITLE
Problem: ZeroMQ 3.2 downloads coming from VM that is about to be shut down

### ISSUE THREAD

**Issue by ewenmcneill** [zeromq/zeromq3-x#124]
The [downloads for ZeroMQ 3.2](http://zeromq.org/intro:get-the-software) are coming from `download.zeromq.org` which is a CNAME to an iMatix VM.  That VM is about to be shut down (somewhere between late May and mid-June).  When that VM is shut down the downloads for ZeroMQ 3.2 will not work if they are not changed.

Suggested solution:
1.   Tag at least the most recent (3.2.5) release in the GitHub repository to create a GitHub release at the commit representing 3.2.5.
2.   Arrange for the auto-builder to run on `zeromq3-x` and upload ready-to-build archives (and/or manually upload the existing archives)
3.   Update [the download page](http://zeromq.org/intro:get-the-software) to link to the GitHub release hosted archives.

Ewen

**Comment by ewenmcneill** [comment]
It looks like there is a [v3.2.5](https://github.com/zeromq/zeromq3-x/releases/tag/v3.2.5) tag already; so in theory it just needs someone with commit access to the `zeromq/zeromq3-x` repository to upload the existing archives (linked from [downloads for ZeroMQ 3.2](http://zeromq.org/intro:get-the-software)) against those releases --- and then update the links.

Ewen

**Comment by hintjens** [comment]
I've added you to this and zeromq4-x and zeromq4-1 as collaborator with
write access, so I think you can do the uploads. I can edit the page on the
wiki after that.

**Comment by ewenmcneill** [comment]
Please update the ZeroMQ 3.2 download links to point at:

https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.tar.gz
https://github.com/zeromq/zeromq3-x/releases/download/v3.2.5/zeromq-3.2.5.zip

and the ZeroMQ 4.1 download links to point at:

https://github.com/zeromq/zeromq4-1/releases/download/v4.1.4/zeromq-4.1.4.tar.gz
https://github.com/zeromq/zeromq4-1/releases/download/v4.1.4/zeromq-4.1.4.zip

and the "previous releases" links to point at:

[Earlier 3.x releases](https://zeromq.github.io/zeromq3-x/)
[Earlier 4.x releases](https://zeromq.github.io/zeromq4-1/)

Plus a note that even older releases have been archived on archive.org, eg at:

https://archive.org/search.php?query=subject%3A%22zeromq%22%20subject%3A%22message_queue%22

(Unfortunately there isn't yet a ZeroMQ Collection; I'll ask again tomorrow if I haven't heard back.)

Ewen

**Comment by hintjens** [comment]
OK, done, thanks.
