### ISSUE TITLE
Access Violation in mailbox_t::recv

### ISSUE THREAD

**Issue by nefelipl** [zeromq/zeromq3-x#127]
Hi all, 

We are using 0mq and it crashes with the following details:

	Unhandled exception at 0x00007FFCCA9395FC (KERNELBASE.dll) in [OURPROCESS].dmp: 0x40000015:  %hs (parameters: 0x00000000522694C0).
	
	libzmq.dll!zmq::mailbox_t::recv(zmq::command_t * cmd_, int timeout_) Line 86	C++
 	libzmq.dll!zmq::socket_base_t::process_commands(int timeout_, bool throttle_) Line 855	C++
 	libzmq.dll!zmq::socket_base_t::getsockopt(int option_, void * optval_, unsigned __int64 * optvallen_) Line 291	C++
 	libzmq.dll!zmq_poll(zmq_pollitem_t * items_, int nitems_, long timeout_) Line 892	C++
	[OURPROCESS]::QPoller::Poll(__int64 timeout) Line 63	C++

Does anyone have any idea on what is going on ? The only thing that I can suspect is that for some reason the machine is running out of sockets. But after investigating the machine this seems unlikely. 

The Windows version is Windows Server 2012 R2.

**Comment by bluca** [comment]
Are you creating/using a socket from multiple threads?

**Comment by nefelipl** [comment]
Hi Luca, thanks for the reaction. No we are not reusing sockets. Each thread has their own socket(pair).

**Comment by bluca** [comment]
Then I would suggest trying with the latest 4.2.x - 3.x is not maintained any longer and is several years old by now

**Comment by nefelipl** [comment]
This issue is caused most likely due to this issue : 

https://github.com/zeromq/libzmq/issues/1542
